### ISSUE TITLE
AVR: Reading of digital inputs not working

### ISSUE THREAD

**Issue by manasdas17** [modelica/Modelica_DeviceDrivers#229]
Hi,
Seems there is an issue with Digital Write functionality in Modelica_DeviceDrivers.Aim of this implementation is to when i press a push button, depending on the input LED should be ON/OFF. But the input from the push button i.e. Digital Write isn't working so there is no change in the LED status.PFA for screenshot of the model.
![digital_write_model](https://user-images.githubusercontent.com/1115602/33161314-a8540b00-d048-11e7-8deb-fcb8262832bc.png)

**Comment by bernhard-thiele** [comment]
@manasdas17 Thanks a lot for that report and the related PR #266 which fixes it! Sorry for taking that long for looking into this issue. I just replicated the issue on my Arduino. Unfortunately, the naming is a bit misleading since it is the reading of digital inputs which has a bug. I will take the liberty to rename the issue.
