### ISSUE TITLE
UDP connector with Mathematical operation

### ISSUE THREAD

**Issue by MustafaSoliman** [modelica/Modelica_DeviceDrivers#232]
I am trying to do an example using UDP function in the library. 
I wanted to take the initial condition for a bouncing ball component using UPD Function. 
as in this example. 
but since there is a delay for the values from UDP, the initials are always zeros and the example fails. 

is there anyway to delay the ball block from asking for the initial values until updated ? 
any other alternatives to make the example ? 

![bouncing ball](https://user-images.githubusercontent.com/36659549/37273137-311a9af2-261c-11e8-9acf-bced02c87f8a.PNG)

thanks

**Comment by bernhard-thiele** [comment]
Yes, you won't get the values during initialization if you use the standard UDP blocks. The packages are always sent and received during events generated by `sample(0,sampleTime)` and thus the initialization is already finished.

You could use the functions layer directly without the blocks and also send or receive data during initialization, but you have no influence on the execution order of the send or receive functions (except if you manage to impose some dummy data flow constraints). A workaround might be to use the `reinit` operator in order to reinitialize the ball within the simulation.

**Comment by MustafaSoliman** [comment]
Thanks, I will try them and get back to you.
