### ISSUE TITLE
Hard-coded eth0 interface in getMACAddress implementation for Linux

### ISSUE THREAD

**Issue by bernhard-thiele** [modelica/Modelica_DeviceDrivers#260]
The Linux implementation assumes that the network interface is called `eth0` and it doesn't support the index argument
(https://github.com/modelica/Modelica_DeviceDrivers/blob/1b988c000dc8b8f86fcfbc011938949e5bdc6467/Modelica_DeviceDrivers/Resources/Include/MDDUtilitiesMAC.h#L117)

- Even for wire-based ethernet interfaces, the name for the interface in Linux is not always `eth0`, hence even if a Linux machine has an ethernet adapter, the function might not correctly retrieve its MAC address.
- What seems more useful is to iterate over all the available interfaces. That is what the Windows implementation does.
- Thinking about it, it seems useful to have a Modelica function that returns an array of all the network interface MAC addresses available on the machine.

**Comment by tbeu** [comment]
> What seems more useful is to iterate over all the available interfaces. That is what the Windows implementation does.

Yes, seems consistent.

> Thinking about it, it seems useful to have a Modelica function that returns an array of all the network interface MAC addresses available on the machine.

That is what I wanted to avoid since the size of the array is not known and you would need another call to determine the size first, which makes it hard to use. Additionally, you can not use it like I intended in https://github.com/tbeu/Modelica_DeviceDrivers/blob/aebc69c53083c3a3cc65acb348ea5e0f6caeb053/Modelica_DeviceDrivers/Blocks/Communication.mo#L538
