### ISSUE TITLE
TCP/IP support wanted?

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_DeviceDrivers#78]
My branch add-TCP/IP-support at tbeu/Modelica_DeviceDrivers contains a not yet final implementation of a TCP/IP socket client (for Windows).
@bernhard-thiele Can you please test and estimate if you want to have this in the library? In Incubate?

**Comment by bernhard-thiele** [comment]
Definitely, TCP/IP support would be nice to have! I wouldn't put it into Incubate, unless you view it is an experimental or incomplete approach.

I just would like to understand whether/why you want to diverge from the data source/sink principle used elsewhere in the library and have everything in one block. Or is this just due to the early prototype?

**Comment by tbeu** [comment]
The reason is that there is only one instance of the external object for the TCP/IP client. This is required for the blocking ```recv``` of the client from the server. Thus it is not possible to separate input and output if I am not wrong.
