### ISSUE TITLE
How to use Arduino Uno 

### ISSUE THREAD

**Issue by manasdas17** [modelica/Modelica_DeviceDrivers#92]
I tried to connect arduino uno board with Openmodelica and Modelica_DeviceDrivers ,but couldn't succeed.Could you plz how to perform the communication between Openmodelica and arduino by using Modelica_DeviceDrivers package.

**Comment by tbeu** [comment]
I can't speak for OpenModelica but the serial port communication should work in general to receive and transmit serial data to/from the Arduino Uno.

**Comment by bernhard-thiele** [comment]
OpenModelica doesn't  yet support external objects in connection equations. This is needed for the communication blocks. Because of that, OpenModelica's support of the library is currently rather limited. I hope that this will improve at some time, but it will need considerable effort (either to change OpenModelica or to change the packaging system).

**Comment by tbeu** [comment]
Maybe it would be nice to have some raw functions for the commucation blocks that avoid the packager external object and just deal with vector of doubles or ints.
